#!/bin/env php
<?php
// Define our Directory Seperator
define('DS', DIRECTORY_SEPARATOR);

// Path to the index folder
$path = dirname(dirname(dirname(__FILE__)));

// Get the current CMS build
$file = file_get_contents($path . DS .'index.php');
if(preg_match('/CMS_BUILD\', ([0-9]+)/', $file, $matches))
{
    // Update the commit message and index file
    file_put_contents($argv[1], "[" . ($matches[1] + 1) ."] ");
    exit(0);
}
else
{
    echo 'No build number found. Please correct the commit message by including the build number "[100]"';
    exit(1);
}
?>